#!/usr/bin/env bash
# Bash script that configure ab Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello world!" > /var/www/html/mary.index
printf %s "server {
	listen 80;
	listen [::]:80 default_server;

	root /var/www/html;
	index mary.index index.html index.nginx-debian.html;

	location /redirect_me {
		return 301 http://youtube.com;
	}
}" > /etc/nginx/sites-available/default
sudo service nginx restart
